### ISSUE TITLE
Is there any plan for adding support to react 18

### ISSUE THREAD

**Issue by realamirhe** [yasamanhbn/Arcaptcha-React-js#1]
Now we must add the resolution for react 18 in our project to support react 17 support for widget
Is there any plan for react +16.8 compatible hooked version oh arcaptach or at least adding support for the new react version?

**Comment by realamirhe** [comment]
any update on this?

**Comment by yasamanhbn** [comment]
> Now we must add the resolution for react 18 in our project to support react 17 support for widget Is there any plan for react +16.8 compatible hooked version oh arcaptach or at least adding support for the new react version?

Hello. I apologize for the delay in replying. I did some changes in this field. Please check if your problem is solved or not.

**Comment by realamirhe** [comment]
Thanks, @yasamanhbn.
I tested the latest version with the Next@13 and everything seems to work soundly.
