### ISSUE TITLE
Is there a way to get the loaded event in react!

### ISSUE THREAD

**Issue by realamirhe** [yasamanhbn/Arcaptcha-React-js#2]
It takes a long time for the first load and we need to implement Skelton loading till ARCaptcha gets loaded, Could you add the `onLoaded` callback prop to be called within here?
https://github.com/yasamanhbn/Arcaptcha-React-js/blob/e0d805d8db90b7a85839ca9f73c20a5cd467518d/src/lib/components/ArcaptchaWidget.js#L28-L31

Now must hackaround with the `window.arcaptchaWidgetLoading` Promise to get the loaded state.

It might also be possible to add event listener on custom events like `arcaptcha-${ref.current.state.widget_id}` if you dispatch a custom event after a load has been done
e.g. DOMContentLoaded

**Comment by yasamanhbn** [comment]
> It takes a long time for the first load and we need to implement Skelton loading till ARCaptcha gets loaded, Could you add the `onLoaded` callback prop to be called within here?
> 
> https://github.com/yasamanhbn/Arcaptcha-React-js/blob/e0d805d8db90b7a85839ca9f73c20a5cd467518d/src/lib/components/ArcaptchaWidget.js#L28-L31
> 
> Now must hackaround with the `window.arcaptchaWidgetLoading` Promise to get the loaded state.
> 
> It might also be possible to add event listener on custom events like `arcaptcha-${ref.current.state.widget_id}` if you dispatch a custom event after a load has been done e.g. DOMContentLoaded

Hi. You can use "rendered_callback".  for more information about this props you should visit https://github.com/arcaptcha/Arcaptcha-React-js

**Comment by realamirhe** [comment]
Hey, I first came up with that idea but failed in passing those props into the react component.
I couldn't find a way to pass that `rendered_callback` (or `renderedCallback`), and because the callback and other props are used in the widget rendering phase, I thought it might not exist at react component.

Could you guide me on how to use it in react component?

https://github.com/yasamanhbn/Arcaptcha-React-js/blob/e0d805d8db90b7a85839ca9f73c20a5cd467518d/src/lib/components/ArcaptchaWidget.js#L69

**Comment by yasamanhbn** [comment]
> Hey, I first came up with that idea but failed in passing those props into the react component. I couldn't find a way to pass that `rendered_callback` (or `renderedCallback`), and because the callback and other props are used in the widget rendering phase, I thought it might not exist at react component.
> 
> Could you guide me on how to use it in react component?
> 
> https://github.com/yasamanhbn/Arcaptcha-React-js/blob/e0d805d8db90b7a85839ca9f73c20a5cd467518d/src/lib/components/ArcaptchaWidget.js#L69

You send your desired function as props ‍‍`rendered_callback` to the widget. Then, when the widget is rendered, your function will be called and you can do your action.

```js
  checkCallback() {
    console.log("widget is rendered");
    //do your action
  }
  render() {
    return (
      <div>
        <ArcaptchaWidget
          ref={this.ArRef}
          site-key="YourSiteKey"
          rendered_callback={this.checkCallback}
          theme="dark" //it's not required. Default is light
          lang="en" //it's not required. Default is fa
        />
      </div>
    );
  }
```

**Comment by realamirhe** [comment]
Thanks, I was searching in the wrong repo (https://github.com/yasamanhbn/Arcaptcha-React-js)
The main ar-captcha repo (https://github.com/arcaptcha/Arcaptcha-React-js) has implemented that functionality 

I post the issues here, because the main repo doesn't have any section for posting issues
