### ISSUE TITLE
execute function should return the internal execute promise

### ISSUE THREAD

**Issue by realamirhe** [yasamanhbn/Arcaptcha-React-js#4]
[execute](https://github.com/arcaptcha/Arcaptcha-React-js/blob/d6d6a8587875c5fd1b9d8def4bf700398efbb26f/src/lib/components/ArcaptchaWidget.js#L62)

```tsx
 execute() {
    window.arcaptcha.execute(this.state.widget_id);
  }
```

ArCaptcha doesn't return the instance of internal `arcaptcha` execute, hence we can not wait for the token in a programmatically way in the invisible (hidden) mode

please return the instance so we can use it in an async await mode

```tsx
 execute() {
    return window.arcaptcha.execute(this.state.widget_id);
  }
```

**Comment by yasamanhbn** [comment]
> [execute](https://github.com/arcaptcha/Arcaptcha-React-js/blob/d6d6a8587875c5fd1b9d8def4bf700398efbb26f/src/lib/components/ArcaptchaWidget.js#L62)
> 
> ```tsx
>  execute() {
>     window.arcaptcha.execute(this.state.widget_id);
>   }
> ```
> 
> ArCaptcha doesn't return the instance of internal `arcaptcha` execute, hence we can not wait for the token in a programmatically way in the invisible (hidden) mode
> 
> please return the instance so we can use it in an async await mode
> 
> ```tsx
>  execute() {
>     return window.arcaptcha.execute(this.state.widget_id);
>   }
> ```

Hi. I've done it. Thanks for the reminder
